a.out: SecondLargestNumber.o IsPalindrome.o Palindrome.o MoveArrayRight.o PrintHighestSequence.o Calculator1.o ex3.o
	gcc SecondLargestNumber.o IsPalindrome.o Palindrome.o MoveArrayRight.o PrintHighestSequence.o Calculator1.o ex3.o

SecondLargestNumber.o: SecondLargestNumber.c SecondLargestNumber.h
	gcc -c SecondLargestNumber.c -lm

IsPalindrome.o: IsPalindrome.c IsPalindrome.h
	gcc -c IsPalindrome.c -lm

Palindrome.o: Palindrome.c Palindrome.h
	gcc -c Palindrome.c -lm

MoveArrayRight.o: MoveArrayRight.c MoveArrayRight.h
	gcc -c MoveArrayRight.c -lm

PrintHighestSequence.o: PrintHighestSequence.c PrintHighestSequence.h
	gcc -c PrintHighestSequence.c -lm

Calculator1.o: Calculator1.c Calculator1.h
	gcc -c Calculator1.c -lm
